package core

import (
	"encoding/json"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func postSaveRequest(s *Service, path, body string) *httptest.ResponseRecorder {
	r := httptest.NewRequest("POST", path, strings.NewReader(body))
	r.Header.Set("X-Tami-Client", "desktop")
	w := httptest.NewRecorder()
	s.Handler(nil).ServeHTTP(w, r)
	return w
}

func TestGeneratedConfigSaveUsesCoreValueAndSafePublish(t *testing.T) {
	s, _ := testService(t)
	dest := filepath.Join(t.TempDir(), "chosen-config.json")
	var suggested string
	s.PickSave = func(name string) (string, error) {
		suggested = name
		return dest, nil
	}

	w := postSaveRequest(s, "/api/config/save", "{invalid arbitrary payload")
	if w.Code != 200 {
		t.Fatalf("status=%d body=%s", w.Code, w.Body.String())
	}
	if suggested != "tamias-config.json" {
		t.Fatalf("suggested name=%q", suggested)
	}
	var response struct {
		Saved bool   `json:"saved"`
		Path  string `json:"path"`
		Name  string `json:"name"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &response); err != nil {
		t.Fatal(err)
	}
	if !response.Saved || response.Path != dest || response.Name != filepath.Base(dest) {
		t.Fatalf("response=%+v", response)
	}
	data, err := os.ReadFile(dest)
	if err != nil {
		t.Fatal(err)
	}
	var exported ConfigurationExport
	if err = json.Unmarshal(data, &exported); err != nil {
		t.Fatal(err)
	}
	if exported.Version != 1 {
		t.Fatalf("saved payload was not generated by Core: version=%d", exported.Version)
	}

	w = postSaveRequest(s, "/api/config/save", "")
	if w.Code != 400 {
		t.Fatalf("existing destination status=%d body=%s", w.Code, w.Body.String())
	}
	dataAfter, err := os.ReadFile(dest)
	if err != nil || string(dataAfter) != string(data) {
		t.Fatalf("existing file was changed: err=%v", err)
	}
}

func TestGeneratedDiagnosticsSaveBrowserFallback(t *testing.T) {
	s, _ := testService(t)
	w := postSaveRequest(s, "/api/diagnostics/save", "not JSON and ignored")
	if w.Code != 200 {
		t.Fatalf("status=%d body=%s", w.Code, w.Body.String())
	}
	var response struct {
		Saved bool           `json:"saved"`
		Name  string         `json:"name"`
		Value map[string]any `json:"value"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &response); err != nil {
		t.Fatal(err)
	}
	if response.Saved || response.Name != "tamias-diagnostics.json" || response.Value["version"] != Version {
		t.Fatalf("unexpected browser fallback: %+v", response)
	}
}

func TestGeneratedSaveCancellationIsAnError(t *testing.T) {
	s, _ := testService(t)
	s.PickSave = func(string) (string, error) { return "", nil }
	w := postSaveRequest(s, "/api/diagnostics/save", "")
	if w.Code != 400 || !strings.Contains(w.Body.String(), "已取消保存") {
		t.Fatalf("status=%d body=%s", w.Code, w.Body.String())
	}
}
