package core

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"path/filepath"
)

// saveGeneratedJSON stores a value generated by Core. The request body is never
// involved, so callers cannot choose or alter the exported content.
func (s *Service) saveGeneratedJSON(suggestedName string, value any) (any, error) {
	if s.PickSave == nil {
		return map[string]any{"saved": false, "name": suggestedName, "value": value}, nil
	}

	dest, err := s.PickSave(suggestedName)
	if err != nil {
		return nil, fmt.Errorf("无法选择保存位置：%w", err)
	}
	if dest == "" {
		return nil, errors.New("已取消保存")
	}
	name := filepath.Base(filepath.Clean(dest))
	if name == "." || name == string(filepath.Separator) || name == "" {
		return nil, errors.New("请选择文件保存位置")
	}

	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("生成导出文件失败：%w", err)
	}
	data = append(data, '\n')
	if err = publishNewFile(dest, bytes.NewReader(data)); err != nil {
		return nil, err
	}
	return map[string]any{"saved": true, "path": dest, "name": name}, nil
}
